apiVersion: v1
kind: Service
metadata:
  name: api-gtw
  namespace: ns1
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: api-gtw
  ports:
    - protocol: TCP
      port: 8080
      targetPort: public-port
      nodePort: 30001
