kind: Deployment
apiVersion: apps/v1
metadata:
  name: deployment1
  namespace: ns1
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: pod2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pod2
    spec:
      containers:
        - name: container
          image: tonitienda/go-proxy-mermaid:0.1.0-arm64
          ports:
            - containerPort: 8080
              name: public-port
          env:
            - name: PORT
              value: "8080"
            - name: SERVICE_NAME
              value: "Pod2"
            - name: NEXT_SERVICE
              value: "http://service1:8080"

      # resources:
      #     limits:
      #       memory: "800Mi"
      #       cpu: "800m"
      #     requests:
      #       memory: "600Mi"
      #       cpu: "400m"
