kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: ns1
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: container
          image: tonitienda/go-proxy-mermaid:0.2.0-arm64
          ports:
            - containerPort: 8080
              name: public-port
          env:
            - name: PORT
              value: "8080"
            - name: SERVICE_NAME
              value: "backend"

      # resources:
      #     limits:
      #       memory: "800Mi"
      #       cpu: "800m"
      #     requests:
      #       memory: "600Mi"
      #       cpu: "400m"
