kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: staging
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # Number of extra pods when updating them (1)
      maxUnavailable: 0 # Number of unavailable pods when updating them (none)
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
    spec:
      containers:
        - name: http-server
          image: tonitienda/go-proxy-mermaid:0.2.0-arm64
          ports:
            - containerPort: 8080
              name: public-port
          # Controlling resource usage
          resources:
            limits:
              memory: "800Mi"
              cpu: "800m"
            requests:
              memory: "600Mi"
              cpu: "400m"
          # Controling healthchecks
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: PORT
              value: "8080"
            - name: SERVICE_NAME
              value: "backend"
