apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: ns1
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pod1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: public-port
      nodePort: 30007
