apiVersion: v1
kind: Service
metadata:
  name: service3
  namespace: ns2
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: pod3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: public-port
      nodePort: 30003
