apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: staging
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: public-port
      nodePort: 30001
