kind: Pod
apiVersion: v1
metadata:
  name: api
  namespace: develop
  labels:
    app.kubernetes.io/name: api
spec:
  containers:
    - name: container1
      image: tonitienda/go-proxy-mermaid:0.2.0-arm64
      ports:
        - containerPort: 8080
          name: public-port

      env:
        - name: PORT
          value: "8080"
        - name: SERVICE_NAME
          value: "api"
        - name: NEXT_SERVICE
          value: "http://backend:8080"

  # resources:
  #     limits:
  #       memory: "800Mi"
  #       cpu: "800m"
  #     requests:
  #       memory: "600Mi"
  #       cpu: "400m"
