apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: public-port
